name: check
on:
  push:
    branches-ignore:
      - main # deploy runs on main and calls check
  pull_request:
  workflow_call:
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: ${{ vars.pnpm_version }}
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.node_version }}
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - run: pnpm install
      - run: pnpm format:check
        if: always()
      - run: pnpm types:check
        if: always()
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: ${{ vars.pnpm_version }}
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.node_version }}
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - run: pnpm install
      - run: pnpm test:run
        if: always()
